### ISSUE TITLE
SL.BART will be removed from Super Learner

### ISSUE THREAD

**Issue by artur-sannikov** [himelmallick/IntegratedLearner#10]
I get this warning with my data but not with the example data:

```
Warning: Error in algorithm SL.BART 
  The Algorithm will be removed from the Super Learner (i.e. given weight 0) 
Error in SuperLearner::SuperLearner(Y = Y, X = X, cvControl = cvControl,  : 
  All algorithms dropped from library
```
I guess, the new algorithm to use is `SL.bartMachine`?

**Comment by himelmallick** [comment]
Hi @artur-sannikov - would you be able to send a minimal reproducible example to debug it on my end?

Thanks,
Himel

**Comment by artur-sannikov** [comment]
Hi @himelmallick, there was a conflict with [MOFA2](https://biofam.github.io/MOFA2/)'s `predict()` function. I had to unload it from namespace: `unloadNamespace("MOFA2")`.

Now it works.
