### ISSUE TITLE
`feature_metadata_valid` argument is missing

### ISSUE THREAD

**Issue by artur-sannikov** [himelmallick/IntegratedLearner#11]
The argument `feature_metadata_valid` appears both in [README](https://github.com/himelmallick/IntegratedLearner), and in [vignette](https://htmlpreview.github.io/?https://github.com/himelmallick/IntegratedLearner/blob/master/vignettes/IntegratedLearner.html), but it does not exist.

```R
library(IntegratedLearner)
fit<-IntegratedLearner(feature_table = feature_table,
                               sample_metadata = sample_metadata, 
                               feature_metadata = feature_metadata,
                               feature_table_valid = feature_table_valid,
                               sample_metadata_valid = sample_metadata_valid,
                               feature_metadata_valid = feature_metadata_valid,
                               folds = 5,
                               base_learner = 'SL.randomForest',
                               meta_learner = 'SL.nnls.auc',
                               verbose = TRUE,
                               family=binomial())
```

```
Error in IntegratedLearner(feature_table = feature_table, sample_metadata = sample_metadata,  : 
  unused argument (feature_metadata_valid = feature_metadata_valid)
```

**Comment by artur-sannikov** [comment]
Hey, but I think `feature_metadata_valid` is completely missing from the current version.

**Comment by artur-sannikov** [comment]
Hi, are there any updates @himelmallick?

I think this argument is simply missing from the current version IntegratedLearner.

**Comment by himelmallick** [comment]
Hi @artur-sannikov, this has now been resolved. Thanks for noticing the typo, which had carried over from legacy code. Thank you
