### ISSUE TITLE
Error in installing IntegratedLearner

### ISSUE THREAD

**Issue by oshritshtossel** [himelmallick/IntegratedLearner#3]
We tried to install the package in Google Colab according to the following steps:
```
install.packages("devtools")
library(devtools)
devtools::install_github("himelmallick/IntegratedLearner")
library(IntegratedLearner)
```

We got the following error:
```
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘/tmp/RtmpTilmQz/remotes1974ee1f75f/himelmallick-IntegratedLearner-d46a860/DESCRIPTION’ ... OK
* preparing ‘IntegratedLearner’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘IntegratedLearner_0.0.1.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message in i.p(...):
“installation of package ‘/tmp/RtmpTilmQz/file197260e30a1/IntegratedLearner_0.0.1.tar.gz’ had non-zero exit status”
Error in library(IntegratedLearner): there is no package called ‘IntegratedLearner’
Traceback:

1. library(IntegratedLearner)
```

Running it in R-studio resulted with the same issue.

**Comment by himelmallick** [comment]
Hi @oshritshtossel - thanks for reaching out. I am not sure about Google Colab but I was unable to reproduce the error in RStudio. The error itself does not hint at [dependency or other common issues](https://community.rstudio.com/t/installation-of-package-had-non-zero-exit-status/90450). Would you be able to install all the required packages one by one and try installing IntegratedLearner thereafter? The required packages as of this writing are: SuperLearner, tidyverse, caret, multiview, glmnetUtils, ROCR, quadprog, nloptr. 

I hope this helps,
Himel

**Comment by oshritshtossel** [comment]
After playing with it, and checking in DataSpell, The lib mcmcplots was missing.

Can you update the installation instructions?

```
install.packages(c("devtools", "mcmcplots"))
library(devtools)
devtools::install_github("himelmallick/IntegratedLearner")

library(IntegratedLearner)
```

**Comment by himelmallick** [comment]
Thanks, @oshritshtossel. I just pushed an update to include `mcmcplots` as a dependency which should now be automatically installed as part of the `IntegratedLearner` installation. Great catch!
