### ISSUE TITLE
options(java.parameters = "-Xmx5g")  has to be moved above all library imports

### ISSUE THREAD

**Issue by artur-sannikov** [himelmallick/IntegratedLearner#9]
Currently, `options(java.parameters = "-Xmx5g") ` is below `library(IntegratedLearner)`. I was trying to run the vignette from a Podman (might also be a problem with Docker) container, and `bartMachine` would not load with more that ~500m of memory. After I moved this option setting before any library import, it loads with the set amount of memory.

Containerfile for your reference

```Containerfile
# Fetch base image for R version 4.4.0
FROM rocker/rstudio:4.4.0

# Install Java
RUN apt-get update \
   && apt-get install -y --no-install-recommends \
   openjdk-21-jdk

# Let R find Java files
RUN R CMD javareconf

# Install CRAN packages
RUN R -e 'install.packages(c("bartMachine", "caret", "cowplot", "devtools", "mcmcplots", "rJava", "tidyverse"))'

# Install IntegratedLearner
RUN R -e 'devtools::install_github("himelmallick/IntegratedLearner")'

# Create directory for IntegratedLearner
WORKDIR /root/integratedlearner

# Internal port for RStudio server is 8787
EXPOSE 8787
```

P.S. I may also create a pull request for this Containerfile.

**Comment by himelmallick** [comment]
Hi @artur-sannikov, please feel free to create a pull request for this if you’d like. I’m happy to review and approve it. For now, I’m closing this issue. Thanks for the fix!
